# This tells your app to answer the door for Render
server.port=${PORT:8080}
server.address=0.0.0.0

# This tells Spring Boot to securely connect to Aiven using your Render variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
